type SeedLanguage = {
  name: string
  iso639: string
  iso6392b: string | null
  locale: string
  flag: string
}

export const seedLanguages: SeedLanguage[] = [
  { name: "English",                  iso639: "en",  iso6392b: "eng", locale: "en-US",  flag: "🇺🇸" },
  { name: "Danish",                   iso639: "da",  iso6392b: "dan", locale: "da-DK",  flag: "🇩🇰" },
  { name: "Thai",                     iso639: "th",  iso6392b: "tha", locale: "th-TH",  flag: "🇹🇭" },
  { name: "German",                   iso639: "de",  iso6392b: "ger", locale: "de-DE",  flag: "🇩🇪" },
  { name: "Spanish",                  iso639: "es",  iso6392b: "spa", locale: "es-ES",  flag: "🇪🇸" },
  { name: "French",                   iso639: "fr",  iso6392b: "fre", locale: "fr-FR",  flag: "🇫🇷" },
  { name: "Swedish",                  iso639: "sv",  iso6392b: "swe", locale: "sv-SE",  flag: "🇸🇪" },
  { name: "Norwegian",                iso639: "nb",  iso6392b: "nor", locale: "nb-NO",  flag: "🇳🇴" },
  { name: "Finnish",                  iso639: "fi",  iso6392b: "fin", locale: "fi-FI",  flag: "🇫🇮" },
  { name: "Portuguese",               iso639: "pt",  iso6392b: "por", locale: "pt-BR",  flag: "🇧🇷" },
  { name: "Japanese",                 iso639: "ja",  iso6392b: "jpn", locale: "ja-JP",  flag: "🇯🇵" },
  { name: "Chinese",                  iso639: "zh",  iso6392b: "chi", locale: "zh-CN",  flag: "🇨🇳" },
  { name: "Russian",                  iso639: "ru",  iso6392b: "rus", locale: "ru-RU",  flag: "🇷🇺" },
  { name: "Turkish",                  iso639: "tr",  iso6392b: "tur", locale: "tr-TR",  flag: "🇹🇷" },
  { name: "Korean",                   iso639: "ko",  iso6392b: "kor", locale: "ko-KR",  flag: "🇰🇷" },
  { name: "Vietnamese",               iso639: "vi",  iso6392b: "vie", locale: "vi-VN",  flag: "🇻🇳" },
  { name: "Dutch",                    iso639: "nl",  iso6392b: "dut", locale: "nl-NL",  flag: "🇳🇱" },
  { name: "Italian",                  iso639: "it",  iso6392b: "ita", locale: "it-IT",  flag: "🇮🇹" },
  { name: "Polish",                   iso639: "pl",  iso6392b: "pol", locale: "pl-PL",  flag: "🇵🇱" },
  { name: "Ukrainian",                iso639: "uk",  iso6392b: "ukr", locale: "uk-UA",  flag: "🇺🇦" },
  { name: "Czech",                    iso639: "cs",  iso6392b: "cze", locale: "cs-CZ",  flag: "🇨🇿" },
  { name: "Romanian",                 iso639: "ro",  iso6392b: "rum", locale: "ro-RO",  flag: "🇷🇴" },
  { name: "Hungarian",                iso639: "hu",  iso6392b: "hun", locale: "hu-HU",  flag: "🇭🇺" },
  { name: "Greek",                    iso639: "el",  iso6392b: "gre", locale: "el-GR",  flag: "🇬🇷" },
  { name: "Indonesian",               iso639: "id",  iso6392b: "ind", locale: "id-ID",  flag: "🇮🇩" },
  { name: "Malay",                    iso639: "ms",  iso6392b: "may", locale: "ms-MY",  flag: "🇲🇾" },
  { name: "Hindi",                    iso639: "hi",  iso6392b: "hin", locale: "hi-IN",  flag: "🇮🇳" },
  { name: "Arabic",                   iso639: "ar",  iso6392b: "ara", locale: "ar-SA",  flag: "🇸🇦" },

  { name: "Albanian",                 iso639: "sq",  iso6392b: "alb", locale: "sq-AL",  flag: "🇦🇱" },
  { name: "Armenian",                 iso639: "hy",  iso6392b: "arm", locale: "hy-AM",  flag: "🇦🇲" },
  { name: "Azerbaijani",              iso639: "az",  iso6392b: "aze", locale: "az-AZ",  flag: "🇦🇿" },
  { name: "Basque",                   iso639: "eu",  iso6392b: "baq", locale: "eu-ES",  flag: "🇪🇸" },
  { name: "Belarusian",               iso639: "be",  iso6392b: "bel", locale: "be-BY",  flag: "🇧🇾" },
  { name: "Bengali",                  iso639: "bn",  iso6392b: "ben", locale: "bn-BD",  flag: "🇧🇩" },
  { name: "Bosnian",                  iso639: "bs",  iso6392b: "bos", locale: "bs-BA",  flag: "🇧🇦" },
  { name: "Bulgarian",                iso639: "bg",  iso6392b: "bul", locale: "bg-BG",  flag: "🇧🇬" },
  { name: "Catalan",                  iso639: "ca",  iso6392b: "cat", locale: "ca-ES",  flag: "🇪🇸" },
  { name: "Croatian",                 iso639: "hr",  iso6392b: "hrv", locale: "hr-HR",  flag: "🇭🇷" },
  { name: "Estonian",                 iso639: "et",  iso6392b: "est", locale: "et-EE",  flag: "🇪🇪" },
  { name: "Filipino",                 iso639: "fil", iso6392b: "fil", locale: "fil-PH", flag: "🇵🇭" },
  { name: "Georgian",                 iso639: "ka",  iso6392b: "geo", locale: "ka-GE",  flag: "🇬🇪" },
  { name: "Hebrew",                   iso639: "he",  iso6392b: "heb", locale: "he-IL",  flag: "🇮🇱" },
  { name: "Icelandic",                iso639: "is",  iso6392b: "ice", locale: "is-IS",  flag: "🇮🇸" },
  { name: "Irish",                    iso639: "ga",  iso6392b: "gle", locale: "ga-IE",  flag: "🇮🇪" },
  { name: "Kazakh",                   iso639: "kk",  iso6392b: "kaz", locale: "kk-KZ",  flag: "🇰🇿" },
  { name: "Latvian",                  iso639: "lv",  iso6392b: "lav", locale: "lv-LV",  flag: "🇱🇻" },
  { name: "Lithuanian",               iso639: "lt",  iso6392b: "lit", locale: "lt-LT",  flag: "🇱🇹" },
  { name: "Macedonian",               iso639: "mk",  iso6392b: "mac", locale: "mk-MK",  flag: "🇲🇰" },
  { name: "Serbian",                  iso639: "sr",  iso6392b: "srp", locale: "sr-RS",  flag: "🇷🇸" },
  { name: "Slovak",                   iso639: "sk",  iso6392b: "slo", locale: "sk-SK",  flag: "🇸🇰" },
  { name: "Slovenian",                iso639: "sl",  iso6392b: "slv", locale: "sl-SI",  flag: "🇸🇮" },
  { name: "Tamil",                    iso639: "ta",  iso6392b: "tam", locale: "ta-IN",  flag: "🇮🇳" },
  { name: "Telugu",                   iso639: "te",  iso6392b: "tel", locale: "te-IN",  flag: "🇮🇳" },
  { name: "Urdu",                     iso639: "ur",  iso6392b: "urd", locale: "ur-PK",  flag: "🇵🇰" },
  { name: "Persian",                  iso639: "fa",  iso6392b: "per", locale: "fa-IR",  flag: "🇮🇷" },
  { name: "Swahili",                  iso639: "sw",  iso6392b: "swa", locale: "sw-KE",  flag: "🇰🇪" },
  { name: "Afrikaans",                iso639: "af",  iso6392b: "afr", locale: "af-ZA",  flag: "🇿🇦" },
  { name: "Zulu",                     iso639: "zu",  iso6392b: "zul", locale: "zu-ZA",  flag: "🇿🇦" },

  { name: "English UK",               iso639: "en",  iso6392b: "eng", locale: "en-GB",  flag: "🇬🇧" },
  { name: "English Australia",        iso639: "en",  iso6392b: "eng", locale: "en-AU",  flag: "🇦🇺" },
  { name: "Spanish Latin America",    iso639: "es",  iso6392b: "spa", locale: "es-419", flag: "🌎" },
  { name: "Spanish Mexico",           iso639: "es",  iso6392b: "spa", locale: "es-MX",  flag: "🇲🇽" },
  { name: "Portuguese Portugal",      iso639: "pt",  iso6392b: "por", locale: "pt-PT",  flag: "🇵🇹" },
  { name: "Chinese Traditional",      iso639: "zh",  iso6392b: "chi", locale: "zh-TW",  flag: "🇹🇼" },
  { name: "Chinese Hong Kong",        iso639: "zh",  iso6392b: "chi", locale: "zh-HK",  flag: "🇭🇰" },
  { name: "Arabic Egypt",             iso639: "ar",  iso6392b: "ara", locale: "ar-EG",  flag: "🇪🇬" },

  { name: "Tagalog",                  iso639: "tl",  iso6392b: "tgl", locale: "tl-PH",  flag: "🇵🇭" },
  { name: "Burmese",                  iso639: "my",  iso6392b: "bur", locale: "my-MM",  flag: "🇲🇲" },
  { name: "Khmer",                    iso639: "km",  iso6392b: "khm", locale: "km-KH",  flag: "🇰🇭" },
  { name: "Lao",                      iso639: "lo",  iso6392b: "lao", locale: "lo-LA",  flag: "🇱🇦" },
  { name: "Mongolian",                iso639: "mn",  iso6392b: "mon", locale: "mn-MN",  flag: "🇲🇳" },
  { name: "Nepali",                   iso639: "ne",  iso6392b: "nep", locale: "ne-NP",  flag: "🇳🇵" },
  { name: "Sinhala",                  iso639: "si",  iso6392b: "sin", locale: "si-LK",  flag: "🇱🇰" },
  { name: "Gujarati",                 iso639: "gu",  iso6392b: "guj", locale: "gu-IN",  flag: "🇮🇳" },
  { name: "Kannada",                  iso639: "kn",  iso6392b: "kan", locale: "kn-IN",  flag: "🇮🇳" },
  { name: "Malayalam",                iso639: "ml",  iso6392b: "mal", locale: "ml-IN",  flag: "🇮🇳" },
  { name: "Marathi",                  iso639: "mr",  iso6392b: "mar", locale: "mr-IN",  flag: "🇮🇳" },
  { name: "Punjabi",                  iso639: "pa",  iso6392b: "pan", locale: "pa-IN",  flag: "🇮🇳" },

  { name: "Luxembourgish",            iso639: "lb",  iso6392b: "ltz", locale: "lb-LU",  flag: "🇱🇺" },
  { name: "Maltese",                  iso639: "mt",  iso6392b: "mlt", locale: "mt-MT",  flag: "🇲🇹" },
  { name: "Welsh",                    iso639: "cy",  iso6392b: "wel", locale: "cy-GB",  flag: "🏴" },
  { name: "Scottish Gaelic",          iso639: "gd",  iso6392b: "gla", locale: "gd-GB",  flag: "🏴" },
  { name: "Galician",                 iso639: "gl",  iso6392b: "glg", locale: "gl-ES",  flag: "🇪🇸" },

  { name: "Amharic",                  iso639: "am",  iso6392b: "amh", locale: "am-ET",  flag: "🇪🇹" },
  { name: "Hausa",                    iso639: "ha",  iso6392b: "hau", locale: "ha-NG",  flag: "🇳🇬" },
  { name: "Igbo",                     iso639: "ig",  iso6392b: "ibo", locale: "ig-NG",  flag: "🇳🇬" },
  { name: "Yoruba",                   iso639: "yo",  iso6392b: "yor", locale: "yo-NG",  flag: "🇳🇬" },
  { name: "Somali",                   iso639: "so",  iso6392b: "som", locale: "so-SO",  flag: "🇸🇴" },

  { name: "Kyrgyz",                   iso639: "ky",  iso6392b: "kir", locale: "ky-KG",  flag: "🇰🇬" },
  { name: "Tajik",                    iso639: "tg",  iso6392b: "tgk", locale: "tg-TJ",  flag: "🇹🇯" },
  { name: "Turkmen",                  iso639: "tk",  iso6392b: "tuk", locale: "tk-TM",  flag: "🇹🇲" },
  { name: "Uzbek",                    iso639: "uz",  iso6392b: "uzb", locale: "uz-UZ",  flag: "🇺🇿" },

  { name: "Esperanto",                iso639: "eo",  iso6392b: "epo", locale: "eo-001", flag: "🌍" },
  { name: "Latin",                    iso639: "la",  iso6392b: "lat", locale: "la-VA",  flag: "🇻🇦" },
]
