export const permissionNotes = [
  { key: "canManageWorker", label: "Manage Worker", desc: "Pause or resume the translation worker." },
  { key: "canAddSubtitleToTranslateDashboard", label: "Upload Subtitles (Dashboard)", desc: "Upload SRT files directly from the dashboard for translation." },
  { key: "canAddSubtitleToTranslateFromLibrary", label: "Request Library Translation", desc: "Queue translations from the library path request flow." },
  { key: "canChangeSubtitlePriority", label: "Change Subtitle Priority", desc: "Reorder and reprioritise subtitle jobs in the queue." },
  { key: "canCancelTranslationJob", label: "Cancel Translation Job", desc: "Cancel or stop running translation jobs." },
  { key: "canDeleteTranslation", label: "Delete Translation", desc: "Delete subtitles and their associated translation data." },
  { key: "canViewLogsDashboard", label: "View Logs (Dashboard)", desc: "View the recent log feed shown on the dashboard." },
  { key: "canRestartTranslationChunk", label: "Restart Chunk", desc: "Retry failed or stuck translation chunks." },
  { key: "canDownloadFinishedSubtitles", label: "Download Subtitles", desc: "Download and export completed translated subtitle files." },
  { key: "canViewFinishedTranslatedPage", label: "View Translated Page", desc: "Access the Translated page listing finished subtitle jobs." },
  { key: "canViewModelsPage", label: "View Models", desc: "View configured AI models and their roles." },
  { key: "canAddOrInstallAModel", label: "Add / Install Model", desc: "Add or install AI models (including pulling from Ollama)." },
  { key: "canEditModels", label: "Edit Models", desc: "Edit existing model settings." },
  { key: "canManageModelRoles", label: "Manage Model Roles", desc: "Assign or remove translation/judge roles for models." },
  { key: "canRemoveAndDeleteModels", label: "Remove / Delete Models", desc: "Remove models from the system and delete them from Ollama." },
  { key: "canViewPromptsPage", label: "View Prompts", desc: "View prompt templates and their versions." },
  { key: "canManagePrompts", label: "Manage Prompts", desc: "Create, edit, activate, and manage prompt templates." },
  { key: "canViewStatistics", label: "View Statistics", desc: "View translation, model, and prompt statistics." },
  { key: "canViewUsers", label: "View Users", desc: "View the user list." },
  { key: "canEditPermissions", label: "Edit Permissions", desc: "Directly edit permission grants (reserved for system use)." },
  { key: "canChangeOtherUsersPassword", label: "Change Other Users' Password", desc: "Reset the password of another user." },
  { key: "canManageRoles", label: "Manage Roles", desc: "Assign or remove roles for other users." },
  { key: "canAddUser", label: "Add User", desc: "Create new user accounts." },
  { key: "canViewLibraryPathsPage", label: "View Library Paths", desc: "View the library paths management page." },
  { key: "canChangeMatchForLibraryPaths", label: "Change Media Match", desc: "Update the media item matched to a library path item." },
  { key: "canAddPathForLibraryPaths", label: "Add Library Path", desc: "Create new library scanning paths." },
  { key: "canBlackListALibraryPathItem", label: "Blacklist Library Item", desc: "Blacklist or un-blacklist library path items." },
  { key: "canEditLibraryPath", label: "Edit Library Path", desc: "Edit existing library path settings." },
  { key: "canDisableAndDeleteALibraryPath", label: "Disable / Delete Library Path", desc: "Disable or permanently delete a library path." },
  { key: "canViewOffsetPage", label: "View Offset Page", desc: "Access the Offset page to view and apply SRT offset adjustments." },
  { key: "canEditSubtitleOffsets", label: "Edit Subtitle Offsets", desc: "Apply a time offset to a subtitle file via the Offset page." },
  { key: "canViewSettingsPage", label: "View Settings", desc: "Access the settings / configuration page." },
  { key: "canManageSettings", label: "Manage Settings", desc: "Change application settings, languages, themes, and root library path." },
  { key: "canManageSecrets", label: "Manage Secrets", desc: "View and manage API key secrets." },
  { key: "canViewSchedules", label: "View Schedules", desc: "View translation schedule windows." },
  { key: "canManageSchedules", label: "Manage Schedules", desc: "Create, edit, and delete translation schedule windows." },
  { key: "canViewLogs", label: "View Logs (Full)", desc: "Access the paginated logs page with full log history." },
] as const
