# shellcheck shell=bash
# Shared helpers for setup scripts. Sourced — not run directly.

# Colourised status lines. No-op if NO_COLOR is set.
if [[ -z "${NO_COLOR:-}" && -t 1 ]]; then
  C_BLUE='\033[34m'; C_GREEN='\033[32m'; C_YELLOW='\033[33m'; C_RED='\033[31m'; C_DIM='\033[2m'; C_OFF='\033[0m'
else
  C_BLUE=''; C_GREEN=''; C_YELLOW=''; C_RED=''; C_DIM=''; C_OFF=''
fi

step()  { printf "${C_BLUE}==>${C_OFF} %s\n" "$*"; }
ok()    { printf "${C_GREEN}OK${C_OFF}  %s\n" "$*"; }
warn()  { printf "${C_YELLOW}!!${C_OFF}  %s\n" "$*" >&2; }
fail()  { printf "${C_RED}xx${C_OFF}  %s\n" "$*" >&2; exit 1; }

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || fail "Required command not found: $1${2:+ ($2)}"
}

require_docker() {
  require_cmd docker "install Docker Desktop or the Docker Engine"
  if ! docker compose version >/dev/null 2>&1; then
    fail "Docker Compose v2 plugin not found. Update Docker or install the compose plugin."
  fi
  if ! docker info >/dev/null 2>&1; then
    fail "Docker daemon is not reachable. Start Docker Desktop / the docker service and retry."
  fi
}

# Create .env from .env.example if missing and fill in a random AES_KEY
# when blank. Existing values are never overwritten.
ensure_env_file() {
  local root="$1"
  local env_file="$root/.env"
  local example="$root/.env.example"

  if [[ ! -f "$env_file" ]]; then
    if [[ ! -f "$example" ]]; then
      fail "Neither .env nor .env.example exists at $root"
    fi
    cp "$example" "$env_file"
    ok "Created .env from .env.example"
  fi

  # Generate AES_KEY if the value is empty. AES-256-GCM needs a 32-byte key
  # (64 hex chars).
  if grep -Eq '^AES_KEY=[[:space:]]*$' "$env_file"; then
    require_cmd openssl "needed to generate a random AES_KEY"
    local key
    key="$(openssl rand -hex 32)"
    # Portable in-place edit (BSD + GNU sed) via tmpfile.
    local tmp
    tmp="$(mktemp)"
    awk -v k="$key" 'BEGIN{done=0} /^AES_KEY=/{ if(!done){print "AES_KEY="k; done=1; next} } {print}' "$env_file" > "$tmp"
    mv "$tmp" "$env_file"
    ok "Generated random AES_KEY in .env"
  fi

  # Ensure Whisper environment placeholders exist so the file is complete.
  if ! grep -Eq '^WHISPER_MODEL_ROOT_PATH=' "$env_file"; then
    printf '\n# Whisper model cache directory.\nWHISPER_MODEL_ROOT_PATH=\n' >> "$env_file"
  fi
  if ! grep -Eq '^WHISPER_GPU_AVAILABLE=' "$env_file"; then
    printf '\n# Set to 1 to allow CUDA for Whisper (added by setup.sh for NVIDIA).\nWHISPER_GPU_AVAILABLE=\n' >> "$env_file"
  fi
}

# Print a "what's next" footer.
print_done_banner() {
  local port="${HOST_PORT:-4850}"
  echo
  ok "BCookieSubs is up."
  echo "    Browse:  http://localhost:${port}"
  echo "    Logs:    docker compose $1 logs -f app"
  echo "    Stop:    docker compose $1 down"
}

# ─── docker-compose file generators ───────────────────────────────────────────
# setup.sh (and the variant setup scripts) own the compose files below. They are
# regenerated each run — do NOT hand-edit them; re-run setup.sh instead. The base
# files stay env-parameterized (via ${VAR:-default}) so .env values are read at
# `docker compose up` time, never baked into the generated file.

# Base topology: app + dockerised Ollama + Whisper (CPU). GPU passthrough is added
# by a generated docker-compose.gpu.yml overlay; macOS uses docker-compose.macos.yml.
write_compose_base() {
  local root="$1"
  cat > "$root/docker-compose.yml" <<'COMPOSE'
# BCookieSubs — docker-compose (GENERATED by setup.sh — do not hand-edit)
#
# Base topology: app + dockerised Ollama + Whisper (CPU). GPU passthrough for the
# dockerised Ollama is added by a generated docker-compose.gpu.yml overlay
# (NVIDIA devices or AMD ROCm), selected by setup.sh when a GPU is detected.
# macOS uses docker-compose.macos.yml (host Ollama + Metal) instead of this file.
#
# Notes:
#   - The app talks to Ollama over the docker network at http://ollama:11434.
#     DISABLE_OLLAMA_SPAWN=1 prevents the app container from trying to spawn
#     its own `ollama serve` (the binary isn't installed in the app image).
#   - TRANSLATION_ROOT_DIR is mirrored at the same path inside the container, so
#     paths typed in the UI match what the container sees (no /media translation).

services:
  app:
    build: .
    image: bcookiesubs:latest
    pull_policy: build
    container_name: bcookiesubs-app
    restart: unless-stopped
    depends_on:
      - ollama
    ports:
      - "${HOST_PORT:-4850}:4850"
    # Forward every .env var to the container (e.g. APP_DEFAULT_LANGUAGE,
    # GPU_TYPE) — the explicit `environment:` block below only lists the
    # container-specific overrides (PORT, DBPATH, OLLAMA_BASE_URL, ...) and
    # takes precedence over env_file for the keys it sets.
    env_file:
      - .env
    environment:
      PORT: "4850"
      DBPATH: "/data/subtitles.db"
      DISABLE_OLLAMA_SPAWN: "1"
      OLLAMA_BASE_URL: "http://ollama:11434"
      AES_KEY: "${AES_KEY}"
      THEMOVIEDB_API_KEY: "${THEMOVIEDB_API_KEY:-}"
      OLLAMA_API_KEY: "${OLLAMA_API_KEY:-}"
      OPENAI_API_KEY: "${OPENAI_API_KEY:-}"
      ANTHROPIC_API_KEY: "${ANTHROPIC_API_KEY:-}"
      TRANSLATION_ROOT_DIR: "${TRANSLATION_ROOT_DIR:-/media}"
      INTERNAL_API_TOKEN: "${INTERNAL_API_TOKEN:-}"
      WHISPER_MODEL_ROOT_PATH: "${WHISPER_MODEL_ROOT_PATH:-/data/whisper-models}"
      WHISPER_GPU_AVAILABLE: "${WHISPER_GPU_AVAILABLE:-}"
    volumes:
      - app-data:/data
      - app-photos:/app/mediaItemPhotos
      - whisper-models:/data/whisper-models
      - "${TRANSLATION_ROOT_DIR:-./media}:${TRANSLATION_ROOT_DIR:-/media}"

  ollama:
    image: ollama/ollama:latest
    container_name: bcookiesubs-ollama
    restart: unless-stopped
    volumes:
      - ollama-models:/root/.ollama
    ports:
      - "${OLLAMA_HOST_PORT:-11434}:11434"
    # GPU passthrough is added by the generated docker-compose.gpu.yml overlay
    # (NVIDIA or AMD/ROCm). CPU-only when no overlay is layered on top.

volumes:
  app-data:
  app-photos:
  ollama-models:
  whisper-models:
COMPOSE
}

# macOS variant: skips the dockerised Ollama and uses a NATIVE Ollama on the Mac
# host (Metal GPU acceleration), reached via host.docker.internal. Docker Desktop
# on macOS has no GPU passthrough (neither NVIDIA nor Apple Silicon).
write_compose_macos() {
  local root="$1"
  cat > "$root/docker-compose.macos.yml" <<'COMPOSE'
# BCookieSubs — docker-compose for macOS (GENERATED by setup.sh — do not hand-edit)
#
# Uses a NATIVE Ollama on the Mac host (Metal GPU acceleration), since Docker
# Desktop on macOS has no GPU passthrough. The app container reaches it at
# http://host.docker.internal:11434.
#
# How the app reaches Ollama:
#   host.docker.internal resolves to the Mac host from inside the container.

services:
  app:
    build: .
    image: bcookiesubs:latest
    pull_policy: build
    container_name: bcookiesubs-app
    restart: unless-stopped
    ports:
      - "${HOST_PORT:-4850}:4850"
    # Required so host.docker.internal works on every Docker Desktop variant
    # (Docker Desktop adds this automatically, but listing it makes it portable
    # to OrbStack / Colima / Rancher Desktop without surprises).
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # Forward every .env var to the container (e.g. APP_DEFAULT_LANGUAGE,
    # GPU_TYPE) — the explicit `environment:` block below only lists the
    # container-specific overrides (PORT, DBPATH, OLLAMA_BASE_URL, ...) and
    # takes precedence over env_file for the keys it sets.
    env_file:
      - .env
    environment:
      PORT: "4850"
      DBPATH: "/data/subtitles.db"
      DISABLE_OLLAMA_SPAWN: "1"
      OLLAMA_BASE_URL: "http://host.docker.internal:11434"
      AES_KEY: "${AES_KEY}"
      THEMOVIEDB_API_KEY: "${THEMOVIEDB_API_KEY:-}"
      OLLAMA_API_KEY: "${OLLAMA_API_KEY:-}"
      OPENAI_API_KEY: "${OPENAI_API_KEY:-}"
      ANTHROPIC_API_KEY: "${ANTHROPIC_API_KEY:-}"
      TRANSLATION_ROOT_DIR: "${TRANSLATION_ROOT_DIR:-/media}"
      INTERNAL_API_TOKEN: "${INTERNAL_API_TOKEN:-}"
      # macOS Docker has no GPU passthrough — Whisper always runs CPU-only.
      WHISPER_MODEL_ROOT_PATH: "${WHISPER_MODEL_ROOT_PATH:-/data/whisper-models}"
      WHISPER_GPU_AVAILABLE: "${WHISPER_GPU_AVAILABLE:-}"
    volumes:
      - app-data:/data
      - whisper-models:/data/whisper-models
      - "${TRANSLATION_ROOT_DIR:-./media}:${TRANSLATION_ROOT_DIR:-/media}"

volumes:
  app-data:
  whisper-models:
COMPOSE
}

# GPU passthrough overlay, layered on docker-compose.yml:
#   docker compose -f docker-compose.yml -f docker-compose.gpu.yml up -d
#   <type> = nvidia | amd
write_compose_gpu() {
  local root="$1" type="$2"
  if [[ "$type" == "nvidia" ]]; then
    cat > "$root/docker-compose.gpu.yml" <<'COMPOSE'
# BCookieSubs — GPU passthrough overlay (GENERATED by setup.sh — do not hand-edit)
# NVIDIA variant. Layer on top of docker-compose.yml:
#   docker compose -f docker-compose.yml -f docker-compose.gpu.yml up -d
# Requires nvidia-container-toolkit on the host:
#   https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/

services:
  app:
    environment:
      WHISPER_GPU_AVAILABLE: "1"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  ollama:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
COMPOSE
  elif [[ "$type" == "amd" ]]; then
    cat > "$root/docker-compose.gpu.yml" <<'COMPOSE'
# BCookieSubs — GPU passthrough overlay (GENERATED by setup.sh — do not hand-edit)
# AMD (ROCm) variant. Layer on top of docker-compose.yml:
#   docker compose -f docker-compose.yml -f docker-compose.gpu.yml up -d
#
# Per Ollama docs: use the ollama/ollama:rocm image and pass the AMD device nodes
# /dev/kfd (HSA kernel driver) and /dev/dri (DRI render nodes). The
# deploy.resources.reservations.devices "driver: amd" form is NOT supported by
# Docker Compose — AMD GPU access is done via device-node passthrough.
# Host prerequisites: ROCm installed (provides /dev/kfd and /dev/dri/*).
# whisper.cpp has no ROCm backend, so the app/Whisper stays CPU-only on AMD; only
# the Ollama inference container gets the GPU.

services:
  ollama:
    image: ollama/ollama:rocm
    devices:
      - "/dev/kfd"
      - "/dev/dri"
COMPOSE
  else
    remove_compose_gpu "$root"
  fi
}

# Remove any stale GPU overlay (CPU/macOS use no GPU overlay).
remove_compose_gpu() {
  local root="$1"
  rm -f "$root/docker-compose.gpu.yml"
}

# Detect the GPU type on Linux. Precedence: NVIDIA -> AMD -> CPU.
#   nvidia : nvidia-smi present (NVIDIA driver loaded)
#   amd    : /dev/kfd present (amdgpu/ROCm kernel driver node — the device the
#            ollama/ollama:rocm container actually needs)
#   cpu    : otherwise
# We deliberately do NOT fall back to `rocminfo` or `lspci` string matches: those
# false-positive on CPU-only boxes that merely have a ROCm package installed or
# a dormant AMD/ATI/Radeon string in PCI space (the script would then report
# "AMD" while /dev/kfd is absent — a contradiction). /dev/kfd is the real
# "a usable AMD GPU + ROCm stack is present" signal. If you have an AMD GPU but
# ROCm isn't installed yet, /dev/kfd is absent → we report CPU; install ROCm and
# re-run setup.sh and this will flip to amd.
# macOS is handled by the caller (metal) — this is Linux-only.
detect_gpu_type() {
  if command -v nvidia-smi >/dev/null 2>&1; then
    echo nvidia; return
  fi
  if [[ -e /dev/kfd ]]; then echo amd; return; fi
  echo cpu
}
