export const recommendedSeeds: [string, string, string | null, string, number, string][] = [
  ["gemma4:31b", "ollama", null, "translation, judge, nameFormatter", 0, "99% accurate · Slow · Handles profanity"],
  ["gemma4:26b", "ollama", null, "translation, judge, nameFormatter", 0, "85% accurate · Medium · Handles profanity"],
  ["qwen3.6:27b", "ollama", null, "translation, judge, nameFormatter", 0, "90% accurate · Slow · Handles profanity"],
  [
    "translategemma:27b",
    "ollama",
    null,
    "translation, judge, nameFormatter",
    0,
    "80% accurate · Fast · Limited profanity",
  ],
  [
    "translategemma:12b",
    "ollama",
    null,
    "translation, judge, nameFormatter",
    0,
    "70% accurate · Fast · Limited profanity",
  ],
  ["granite4.1:3b", "ollama", null, "nameFormatter", 0, "Name detection only · Fast"],
  [
    "qwen3.5:397b-cloud",
    "ollama cloud",
    "https://ollama.com",
    "translation, judge, nameFormatter",
    1,
    "95% accurate · Slow · Handles profanity",
  ],
  [
    "gemma4:31b-cloud",
    "ollama cloud",
    "https://ollama.com",
    "translation, judge, nameFormatter",
    1,
    "99% accurate · Very Fast · Handles profanity",
  ],
  [
    "deepseek-v4-flash:cloud",
    "ollama cloud",
    "https://ollama.com",
    "translation, judge, nameFormatter",
    1,
    "90% accurate · Fast · Handles profanity",
  ],
  [
    "deepseek-v4-pro:cloud",
    "ollama cloud",
    "https://ollama.com",
    "translation, judge, nameFormatter",
    1,
    "99% accurate · Slow · Handles profanity",
  ],
  [
    "glm-5.1:cloud",
    "ollama cloud",
    "https://ollama.com",
    "translation, judge, nameFormatter",
    1,
    "95% accurate · Slow · Handles profanity",
  ],
]
