namespace BCookieSubs.Shared.Database.Seeding;

public static class LanguageSeedData
{
    public sealed record Row(string Name, string Iso639, string? Iso6392B, string Locale, string Flag);

    public static readonly IReadOnlyList<Row> Rows =
    [
    new("English", "en", "eng", "en-US", "🇺🇸"),
    new("Danish", "da", "dan", "da-DK", "🇩🇰"),
    new("Thai", "th", "tha", "th-TH", "🇹🇭"),
    new("German", "de", "ger", "de-DE", "🇩🇪"),
    new("Spanish", "es", "spa", "es-ES", "🇪🇸"),
    new("French", "fr", "fre", "fr-FR", "🇫🇷"),
    new("Swedish", "sv", "swe", "sv-SE", "🇸🇪"),
    new("Norwegian", "nb", "nor", "nb-NO", "🇳🇴"),
    new("Finnish", "fi", "fin", "fi-FI", "🇫🇮"),
    new("Portuguese", "pt", "por", "pt-BR", "🇧🇷"),
    new("Japanese", "ja", "jpn", "ja-JP", "🇯🇵"),
    new("Chinese", "zh", "chi", "zh-CN", "🇨🇳"),
    new("Russian", "ru", "rus", "ru-RU", "🇷🇺"),
    new("Turkish", "tr", "tur", "tr-TR", "🇹🇷"),
    new("Korean", "ko", "kor", "ko-KR", "🇰🇷"),
    new("Vietnamese", "vi", "vie", "vi-VN", "🇻🇳"),
    new("Dutch", "nl", "dut", "nl-NL", "🇳🇱"),
    new("Italian", "it", "ita", "it-IT", "🇮🇹"),
    new("Polish", "pl", "pol", "pl-PL", "🇵🇱"),
    new("Ukrainian", "uk", "ukr", "uk-UA", "🇺🇦"),
    new("Czech", "cs", "cze", "cs-CZ", "🇨🇿"),
    new("Romanian", "ro", "rum", "ro-RO", "🇷🇴"),
    new("Hungarian", "hu", "hun", "hu-HU", "🇭🇺"),
    new("Greek", "el", "gre", "el-GR", "🇬🇷"),
    new("Indonesian", "id", "ind", "id-ID", "🇮🇩"),
    new("Malay", "ms", "may", "ms-MY", "🇲🇾"),
    new("Hindi", "hi", "hin", "hi-IN", "🇮🇳"),
    new("Arabic", "ar", "ara", "ar-SA", "🇸🇦"),
    new("Albanian", "sq", "alb", "sq-AL", "🇦🇱"),
    new("Armenian", "hy", "arm", "hy-AM", "🇦🇲"),
    new("Azerbaijani", "az", "aze", "az-AZ", "🇦🇿"),
    new("Basque", "eu", "baq", "eu-ES", "🇪🇸"),
    new("Belarusian", "be", "bel", "be-BY", "🇧🇾"),
    new("Bengali", "bn", "ben", "bn-BD", "🇧🇩"),
    new("Bosnian", "bs", "bos", "bs-BA", "🇧🇦"),
    new("Bulgarian", "bg", "bul", "bg-BG", "🇧🇬"),
    new("Catalan", "ca", "cat", "ca-ES", "🇪🇸"),
    new("Croatian", "hr", "hrv", "hr-HR", "🇭🇷"),
    new("Estonian", "et", "est", "et-EE", "🇪🇪"),
    new("Filipino", "fil", "fil", "fil-PH", "🇵🇭"),
    new("Georgian", "ka", "geo", "ka-GE", "🇬🇪"),
    new("Hebrew", "he", "heb", "he-IL", "🇮🇱"),
    new("Icelandic", "is", "ice", "is-IS", "🇮🇸"),
    new("Irish", "ga", "gle", "ga-IE", "🇮🇪"),
    new("Kazakh", "kk", "kaz", "kk-KZ", "🇰🇿"),
    new("Latvian", "lv", "lav", "lv-LV", "🇱🇻"),
    new("Lithuanian", "lt", "lit", "lt-LT", "🇱🇹"),
    new("Macedonian", "mk", "mac", "mk-MK", "🇲🇰"),
    new("Serbian", "sr", "srp", "sr-RS", "🇷🇸"),
    new("Slovak", "sk", "slo", "sk-SK", "🇸🇰"),
    new("Slovenian", "sl", "slv", "sl-SI", "🇸🇮"),
    new("Tamil", "ta", "tam", "ta-IN", "🇮🇳"),
    new("Telugu", "te", "tel", "te-IN", "🇮🇳"),
    new("Urdu", "ur", "urd", "ur-PK", "🇵🇰"),
    new("Persian", "fa", "per", "fa-IR", "🇮🇷"),
    new("Swahili", "sw", "swa", "sw-KE", "🇰🇪"),
    new("Afrikaans", "af", "afr", "af-ZA", "🇿🇦"),
    new("Zulu", "zu", "zul", "zu-ZA", "🇿🇦"),
    new("English UK", "en", "eng", "en-GB", "🇬🇧"),
    new("English Australia", "en", "eng", "en-AU", "🇦🇺"),
    new("Spanish Latin America", "es", "spa", "es-419", "🌎"),
    new("Spanish Mexico", "es", "spa", "es-MX", "🇲🇽"),
    new("Portuguese Portugal", "pt", "por", "pt-PT", "🇵🇹"),
    new("Chinese Traditional", "zh", "chi", "zh-TW", "🇹🇼"),
    new("Chinese Hong Kong", "zh", "chi", "zh-HK", "🇭🇰"),
    new("Arabic Egypt", "ar", "ara", "ar-EG", "🇪🇬"),
    new("Tagalog", "tl", "tgl", "tl-PH", "🇵🇭"),
    new("Burmese", "my", "bur", "my-MM", "🇲🇲"),
    new("Khmer", "km", "khm", "km-KH", "🇰🇭"),
    new("Lao", "lo", "lao", "lo-LA", "🇱🇦"),
    new("Mongolian", "mn", "mon", "mn-MN", "🇲🇳"),
    new("Nepali", "ne", "nep", "ne-NP", "🇳🇵"),
    new("Sinhala", "si", "sin", "si-LK", "🇱🇰"),
    new("Gujarati", "gu", "guj", "gu-IN", "🇮🇳"),
    new("Kannada", "kn", "kan", "kn-IN", "🇮🇳"),
    new("Malayalam", "ml", "mal", "ml-IN", "🇮🇳"),
    new("Marathi", "mr", "mar", "mr-IN", "🇮🇳"),
    new("Punjabi", "pa", "pan", "pa-IN", "🇮🇳"),
    new("Luxembourgish", "lb", "ltz", "lb-LU", "🇱🇺"),
    new("Maltese", "mt", "mlt", "mt-MT", "🇲🇹"),
    new("Welsh", "cy", "wel", "cy-GB", "🏴"),
    new("Scottish Gaelic", "gd", "gla", "gd-GB", "🏴"),
    new("Galician", "gl", "glg", "gl-ES", "🇪🇸"),
    new("Amharic", "am", "amh", "am-ET", "🇪🇹"),
    new("Hausa", "ha", "hau", "ha-NG", "🇳🇬"),
    new("Igbo", "ig", "ibo", "ig-NG", "🇳🇬"),
    new("Yoruba", "yo", "yor", "yo-NG", "🇳🇬"),
    new("Somali", "so", "som", "so-SO", "🇸🇴"),
    new("Kyrgyz", "ky", "kir", "ky-KG", "🇰🇬"),
    new("Tajik", "tg", "tgk", "tg-TJ", "🇹🇯"),
    new("Turkmen", "tk", "tuk", "tk-TM", "🇹🇲"),
    new("Uzbek", "uz", "uzb", "uz-UZ", "🇺🇿"),
    new("Esperanto", "eo", "epo", "eo-001", "🌍"),
    new("Latin", "la", "lat", "la-VA", "🇻🇦"),
    ];
}
